apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: plesio-server
  name: plesio-server
  namespace: default
spec:
  ports:
  - port: 8088
    protocol: UDP
    targetPort: 8088
  selector:
    app: plesio-server
  type: LoadBalancer
status:
  loadBalancer: {}
