apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: plesio-server
  name: plesio-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: plesio-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: plesio-server
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/hallowed-spider-407610/plesio-repo/plesio-server:81bcf7d2d0dacd23fd5d477ba01e52880e60474c
        name: plesio-server
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
status: {}
