apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: plesio-server
  name: plesio-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plesio-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: plesio-server
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/hallowed-spider-407610/plesio-repo/plesio-server
        name: plesio-server
        resources: {}
status: {}
